### ISSUE TITLE
Refined coal duplication bug?

### ISSUE THREAD

**Issue by punto-** [punto-/solar_system_demo#5]
Steps to reproduce:

- open the miner interface
- add some coal and refine
- drag refined coal to miner inventory and press "refine"
- close miner interface and open again
- refined coal is still in miner inventory, drag to player inventory
- player has duplicated refined coal?

probably a UI bug, server doesn't have the same inventory?

**Comment by Facundo15** [comment]
It is a UI bug, when the server processes a resource collection, or refinement, it updates what should be updated and sends the entire inventory to the client.

The client receives it with an Inventory Update OpCode, and updates all the inventory that is subscribed to this event and currently only the inventory listens to it and what you see as "duplicate" is just a node that was not cleaned in the miner's inventory
This also gives the behavior of resetting the order of the items in the UI, since that is something that does not notify the server

**Comment by Facundo15** [comment]
fixed
